name: Exiled Main CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  EXILED_REFERENCES_URL: https://www.exiled.host/build_deps/EA_REFS.zip
  BETA_EXILED_REFERENCES: ${{ github.workspace }}/References

jobs:

  build:

    runs-on: windows-latest
    # Prevent double running for push & pull_request events from the main repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'Exiled-Team/Exiled'

    steps:

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2

    - name: Setup Nuget
      uses: iRebbok/setup-nuget@master

    - uses: actions/checkout@v2.3.4

    - name: Get references
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile ${{ github.workspace }}/References.zip
        Expand-Archive -Path References.zip -DestinationPath ${{ env.BETA_EXILED_REFERENCES }}

    - name: Build
      shell: pwsh
      run: |
        ./build.ps1 -BuildNuGet
        $File = (Get-ChildItem -Path . -Include 'EXILED.*.nupkg' -Recurse).Name
        Out-File -FilePath ${{ github.env }} -InputObject "PackageFile=$File" -Encoding utf-8 -Append

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Results
        path: bin/Release

    - name: Upload nuget package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PackageFile }}
        path: ${{ env.PackageFile }}
