name: Exiled CD

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  EXILED_REFERENCES_URL: https://www.exiled.host/build_deps/EA_REFS.zip
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/References

jobs:

  push:

    runs-on: windows-latest

    steps:

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2

    - name: Setup Nuget
      uses: iRebbok/setup-nuget@master

    - uses: actions/checkout@v2.3.4

    - name: Get references
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://www.exiled.host/build_deps/EA_REFS.zip -OutFile ${{ github.workspace }}/References.zip
        Expand-Archive -Path References.zip -DestinationPath ${{ env.EXILED_REFERENCES_PATH }}

    - name: Build NuGet
      env:
        BETA_EXILED_REFERENCES: ${{ env.EXILED_REFERENCES_PATH }}
      shell: pwsh
      run: |
        ./build.ps1 -BuildNuGet
        $File = (Get-ChildItem -Path . -Include 'EXILED.*.nupkg' -Recurse).Name
        Out-File -FilePath ${{ github.env }} -InputObject "PackageFile=$File" -Encoding utf-8 -Append

    - name: Push NuGet
      shell: pwsh
      run: nuget push ${{ env.PackageFile }} -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
